apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: goupadhygettingstarteddemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goupadhygettingstarteddemo 
    spec:
      containers:
        - name: goupadhygettingstarteddemo 
          image: readyaks.azurecr.io/goupadhygettingstarteddemo 
          ports:
          - containerPort: 3000